routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
|--------------------------------------------------------------------------
| English
|--------------------------------------------------------------------------
|
*/
Route::get('English', function () {
    Session::put('lang', 'English');

    return Redirect('/');
});
/*
|--------------------------------------------------------------------------
| Arabic
|--------------------------------------------------------------------------
|
*/
Route::get('arabic', function () {
    Session::put('lang', 'arabic');

    return Redirect('/');
});
/*
|--------------------------------------------------------------------------
| German
|--------------------------------------------------------------------------
|
*/
Route::get('German', function () {
    Session::put('lang', 'German');

    return Redirect('/');
});

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
|
*/
Auth::routes();
/*
|--------------------------------------------------------------------------
| Home Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('about', 'HomeController@about')->name('about');
Route::get('Contact', 'HomeController@Contact')->name('Contact');

/*
|--------------------------------------------------------------------------
| missing RETURN 404 PAGE Route
|--------------------------------------------------------------------------
|
*/
Route::get('missing', function () {
    return view('404');
});
/*
|--------------------------------------------------------------------------
| dashboardController
|--------------------------------------------------------------------------
|
*/
Route::group(['middleware' => 'admin'], function () {
    Route::resource('admin', 'dashboardController');
    Route::resource('dashboard/dashboardSettings', 'dashboardSettingsController');
    Route::resource('dashboard/dashboardUsers', 'AdminUserController');
    Route::resource('dashboard/dashboardRoles', 'dashboardRoleController');
    Route::resource('dashboard/dashboardPosts', 'dashboardPostController');
    Route::resource('dashboard/dashboardCategores', 'dashboardCategoryController');
    Route::resource('dashboard/dashboardMenus', 'dashboardmenuController');
    Route::resource('dashboard/dashboardMenu-items', 'dashboardmenu_itemController');
    Route::resource('dashboard/dashboardAds', 'dashboardvertiserController');
    Route::resource('dashboard/dashboardCauses', 'dashboardCauseController');
    Route::resource('dashboard/dashboardEvents', 'dashboardEventController');
    Route::resource('dashboard/dashboardMessages', 'dashboardmessageController');
    Route::resource('dashboard/dashboardGalleres', 'dashboardGalleryController');
});
/*
|--------------------------------------------------------------------------
| resource
|--------------------------------------------------------------------------
|
*/
Route::resource('Causes', 'CauseController');
Route::resource('Events', 'EventController');
Route::resource('Posts', 'PostController');
Route::resource('Comments', 'CommentController');
Route::resource('Messages', 'messageController');
// route for processing payment
Route::post('paypal', 'PaymentController@payWithpaypal');
// route for check status of the payment
Route::get('status', 'PaymentController@getPaymentStatus');

app/Http/Controllers/dashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use IsAdmin;
use App\setting;
use App\Role;
use App\User;
use Auth;


class dashboardController extends Controller
{


    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.admin');
    }
    
}

resources/views/dashboard/dashboardAds/create.blade.php
@extends('dashboard.layouts.postmain')

@section('dashboardcontent')
<!-- ============================================================= Content Start ============================================================= -->
<div class="main-content-container container-fluid px-4">
  <!-- ================================================ Page Header ========================================================= -->
  <div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
      <span class="text-uppercase page-subtitle">Ads</span>
      <h3 class="page-title"><i class="icon-feather-aperture"></i> Add Ads</h3>
    </div>
  </div>
  <!-- ================================================ Page Header ========================================================= -->
  <div class="row">
    <div class="col-lg-9 col-md-12">
      <div class="card card-small mb-3">
        <div id="form-container" class="card-body">
          <!-- ================================================ Page dashboard Ads ========================================================= -->
          <form action="{{ route('dashboardAds.store') }}" method="POST"  role="form" enctype="multipart/form-data" class="add-new-post" id="FormID">
            @csrf
            <!-- =================== Page dashboard Ads  select ====================== -->
            <select class="custom-select form-control form-control-lg mb-3" name="Location">
              <option value="Home" selected="">Ads Location</option>
              <option value="Home">Home Footer</option>
              <option value="Category">Category Footer</option>
              <option value="Side">Home Side 1</option>
            </select>
            <!-- =================== Page dashboard Ads  select ====================== -->
            <input class="form-control form-control-lg mb-3" type="text" placeholder="Your Name" name="name">
            <input class="form-control  form-control-lg mb-3" type="text" placeholder="Your Display Name" name="displayname">
            <select class="custom-select form-control form-control-lg mb-3" name="type">
              <option value="0" selected="">Ads Type</option>
              <option value="Image">Image</option>
              <option value="code">AdSense</option>
            </select>
            <!-- ================================================ Page dashboard Ads ========================================================= -->
            <div class="row">
              <div class="col-2">
                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                  <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" 
                     aria-selected="true">
                     <!-- =================== Page dashboard Ads  Image ====================== -->
                    <i class="icon-line-awesome-image"></i> Image</a>
                    <!-- =================== Page dashboard Ads  AdSense ====================== -->
                    <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false"><i class="icon-feather-aperture"></i> AdSense</a>
                  </div>
                </div>
                <div class="col-10">
                  <div class="tab-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                      <input class="form-control form-control-lg mb-3" type="text" placeholder="Your Url Image" name="url">
                      <div class="card card-small edit-user-details mb-4">
                        <div class="card-header p-0" style="border-radius: .375rem;">
                          <div class="edit-user-details__bg">
                            <!-- =================== Page dashboard Ads  AdSense ====================== -->
                            <img src="{{ asset('dashboardassets/images/content-management/3.png') }}" alt="User Details Background Image">
                            <label class="edit-user-details__change-background">
                             <i class="icon-material-outline-add-a-photo mr-1" style="font-size: 22px;top: 3px;"></i> Change Image 
                             <input class="d-none" type="file" name="image">
                           </label>
                         </div>
                       </div>
                     </div>
                   </div>
                    <!-- =================== Page dashboard Ads ====================== -->
                    <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                    <textarea id='edit' name="code"></textarea>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ================================================ Page dashboard Ads ========================================================= -->
        <!-- / Add New Post Form -->
      </div>
      <!-- ================================================ Page dashboard Ads ========================================================= -->
      <div class="col-lg-3 col-md-12">
        <!-- Post Overview -->
        <div class='card card-small mb-3'>
          <div class="card-header border-bottom">
            <h6 class="m-0">Actions</h6>
          </div>
          <div class='card-body p-0'>
           <ul class="list-group list-group-flush">
            <li class="list-group-item p-3">
              <span class="d-flex mb-2">
                <i class="icon-line-awesome-flag mr-1"></i>
                <strong class="mr-1">Status:</strong> Draft

              </span>
              <span class="d-flex mb-2">
                <i class="icon-material-outline-visibility mr-1"></i>
                <strong class="mr-1">Visibility:</strong>
                <strong class="text-success">Public</strong>

              </span>
              <span class="d-flex mb-2">
                <i class="icon-line-awesome-calendar mr-1"></i>
                <strong class="mr-1">Schedule:</strong> Now

              </span>
              <span class="d-flex">
                <i class="icon-line-awesome-bullseye mr-1"></i>
                <strong class="mr-1">Readability:</strong>
                <strong class="text-warning">Ok</strong>
              </span>
            </li>
            <li class="list-group-item d-flex px-3">
                <button class="btn btn-sm btn-accent ml-auto" type="submit">
                  <i class="icon-feather-file-plus"></i> Publish</button>
                </li>
              </ul>
            </form>
          </div>
        </div>
        <!-- / Post Overview -->
        <!-- ================================================ Page dashboard Ads ========================================================= -->
      </div>
    </div>
  </div>
  <!-- ============================================================= Content end ============================================================= -->
  @endsection

resources/views/dashboard/dashboardAds/edit.blade.php
@extends('dashboard.layouts.postmain')

@section('dashboardcontent')
<!-- ============================================================= Content Start ============================================================= -->
<div class="main-content-container container-fluid px-4">
  <!-- Page Header -->
  <div class="page-header row no-gutters py-4">
    <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
      <span class="text-uppercase page-subtitle">Ads</span>
      <h3 class="page-title"><i class="icon-feather-aperture"></i> Add Ads</h3>
    </div>
  </div>
  <!-- ============================================================= Content Start ============================================================= -->
  <!-- End Page Header -->
  <div class="row">
    <div class="col-lg-9 col-md-12">
      <div class="card card-small mb-3">
        <div id="form-container" class="card-body">
          <!-- ============================================================= dashboardAds update ========================= -->
            <form class="add-new-post" action="{{ route('dashboardAds.update',$Ads->name) }}" method="POST"  role="form" enctype="multipart/form-data">
            @csrf
            @method('PUT')
            <!-- ============================================================= dashboardAds update ========================= -->
            <select class="custom-select form-control form-control-lg mb-3" name="Location">
              <option value="{{ $Ads->Location }}" selected="">{{ $Ads->Location }}</option>
              <option value="Home">Home Footer</option>
              <option value="Category">Category Footer</option>
              <option value="Side">Home Side 1</option>
            </select>
            <!-- ============================================================= dashboardAds update ========================= -->
            <input class="form-control form-control-lg mb-3" type="text" placeholder="Your Name" name="name" value="{!! $Ads->name !!}">
            <input class="form-control  form-control-lg mb-3" type="text" placeholder="Your Display Name" name="displayname" value="{!! $Ads->displayname !!}">
            <select class="custom-select form-control form-control-lg mb-3" name="type">
              <option value="{{ $Ads->type }}" selected="">{{ $Ads->type }}</option>
              <option value="Image">Image</option>
              <option value="code">AdSense</option>
            </select>
            <!-- ============================================================= dashboardAds update ========================= -->
            <div class="row">
              <div class="col-2">
                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                  <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" 
                     aria-selected="true">
                    <i class="icon-line-awesome-image"></i> Image</a>
                    <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" 
                       aria-selected="false"><i class="icon-feather-aperture"></i> AdSense</a>
                  </div>
                </div>
                <!-- ============================================================= dashboardAds update ========================= -->
                <div class="col-10">
                  <div class="tab-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                      <input class="form-control form-control-lg mb-3" type="text" placeholder="Your Url Image" name="url" value="{{ $Ads->url }}">
                      <div class="card card-small edit-user-details mb-4">
                        <div class="card-header p-0" style="border-radius: .375rem;">
                          <div class="edit-user-details__bg">
                            <img src="{{ asset($Ads->image) }}" alt="User Details Background Image">
                            <label class="edit-user-details__change-background">
                             <i class="icon-material-outline-add-a-photo mr-1" style="font-size: 22px;top: 3px;"></i> Change Image 
                             <input class="d-none" type="file" name="image" value="{{ $Ads->image }}">
                           </label>
                         </div>
                       </div>
                     </div>
                   </div>
                   <!-- ============================================================= dashboardAds update ========================= -->
                    <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                    <textarea id='edit' name="code"></textarea>
                    <!-- ============================================================= dashboardAds update ========================= -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- / Add New Post Form -->
      </div>
      <div class="col-lg-3 col-md-12">
        <!-- Post Overview -->
        <!-- ============================================================= dashboardAds update ========================= -->
        <div class='card card-small mb-3'>
          <div class="card-header border-bottom">
            <h6 class="m-0">Actions</h6>
          </div>
          <div class='card-body p-0'>
           <ul class="list-group list-group-flush">
            <li class="list-group-item p-3">
              <span class="d-flex mb-2">
                <i class="icon-line-awesome-flag mr-1"></i>
                <strong class="mr-1">Status:</strong> Draft

              </span>
              <span class="d-flex mb-2">
                <i class="icon-material-outline-visibility mr-1"></i>
                <strong class="mr-1">Visibility:</strong>
                <strong class="text-success">Public</strong>

              </span>
              <span class="d-flex mb-2">
                <i class="icon-line-awesome-calendar mr-1"></i>
                <strong class="mr-1">Schedule:</strong> Now

              </span>
              <span class="d-flex">
                <i class="icon-line-awesome-bullseye mr-1"></i>
                <strong class="mr-1">Readability:</strong>
                <strong class="text-warning">Ok</strong>
              </span>
            </li>
            <li class="list-group-item d-flex px-3">
                <button class="btn btn-sm btn-accent ml-auto" type="submit">
                  <i class="icon-feather-file-plus"></i> Publish</button>
                </li>
              </ul>
            </form>
            <!-- ============================================================= dashboardAds update ========================= -->
          </div>
        </div>
        <!-- / Post Overview -->
      </div>
    </div>
  </div>
  <!-- ============================================================= Content Start ============================================================= -->
@endsection

resources/views/dashboard/dashboardAds/index.blade.php
@extends('dashboard.layouts.main')

@section('dashboardcontent')
<!-- ============================================================= Content Start ============================================================= -->
<!-- / .main-navbar -->
@if ($message = Session::get('success'))
<div class="alert alert-royal-blue alert-dismissible fade show mb-0" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  <i class="icon-material-outline-check mx-2"></i>
  <strong>Success!</strong> {{ $message }}</div>
@endif
<!-- ============================================================= Content Start ============================================================= -->
@if ($message = Session::get('Delete'))
<div class="alert alert-royal-blue alert-dismissible fade show mb-0" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
<span aria-hidden="true">×</span>
</button>
<i class="icon-material-outline-check mx-2"></i>
<strong>Delete!</strong> {{ $message }} </div>
@endif
<!-- ============================================================= Content Start ============================================================= -->
    <div class="main-content-container container-fluid px-4">
      <!-- Page Header -->
      <div class="page-header row no-gutters py-4">
        <div class="col-12 col-sm-4 text-center text-sm-left mb-0">
          <span class="text-uppercase page-subtitle"> Ads Management</span>
          <h3 class="page-title"><i class="icon-feather-tv"></i>  Ads  
            <a href="{{ route('dashboardAds.create') }}" class="mb-2 btn btn-success mr-2"><i class="icon-material-outline-add-circle-outline"></i> Add Ads</a></h3>  
          </div>
        </div>
        <!-- ============================================================= Content Start ============================================================= -->
        <div class="row">
          <div class="col-lg-12 mb-4">
            <div class="card card-small lo-stats h-100">
              <div class="card-header border-bottom">
                <h6 class="m-0">Latest  Ads Management</h6>
                <div class="block-handle"></div>
              </div>
              <!-- ============================================================= Content Start ============================================================= -->
              <div class="card-body p-0">
                <div class="container-fluid px-0">
                  <table class="table mb-0">
                    <thead class="py-2 bg-light text-semibold border-bottom">
                      <tr>
                        <th>image - Code</th>
                        <th>Title</th>
                        <th class="text-center">Type</th>
                        <th class="text-center">Location</th>
                        <th class="text-right">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      <!-- ================================ advertisers Content Start ======================== -->
                      @foreach($advertisers as $advertiser)
                      <tr>
                        <td class="lo-stats__image">
                          @if($advertiser->image != null)
                          <img class="border rounded" src="{!! asset($advertiser->image) !!}">
                          @elseif($advertiser->url != null)
                          <img class="border rounded" src="{!! asset($advertiser->url) !!}">
                          @elseif($advertiser->code != null)
                          {!! $advertiser->code !!}
                          @endif
                        </td>
                        <!-- ================================ advertisers Content Start ======================== -->
                        <td class="lo-stats__order-details">
                          <span>{!! substr($advertiser->name, 0, 190) !!}</span>
                          <span>{{ date('M j, Y', strtotime($advertiser->created_at)) }}</span>
                        </td>
                        <!-- ================================ advertisers Content Start ======================== -->
                        <td class="lo-stats__total text-center text-success">{!! $advertiser->type !!}</td>
                        <td class="lo-stats__status">
                          <div class="d-table mx-auto">
                            <span class="badge badge-pill badge-success">{!! $advertiser->Location !!}</span>
                          </div>
                        </td>
                        <!-- ================================ advertisers Content Start ======================== -->
                        <td class="lo-stats__actions">
                          <div class="btn-group d-table ml-auto" role="group" aria-label="Basic example">
                            <a href="{{ URL::to('dashboard/Ads')}}/{{$advertiser->name}}/edit" class="mb-2 btn btn-sm btn-primary">
                              <i class="icon-feather-edit-2"></i> Edit</a>
                            <!-- ================================ delete advertisers Content Start ======================== -->
                            <form action="{{ route('dashboardAds.destroy',$advertiser->id) }}" method="POST" files="true" style="display: inline-block;">
                            @csrf
                            @method('DELETE')
                            <button class="mb-2 btn btn-sm btn-danger" type="submit"><i class="icon-material-outline-delete"></i> Delete</button>
                          </form>
                          </div>
                        </td>
                      </tr>
                      @endforeach
                      <!-- ================================ advertisers Content Start ======================== -->
                    </tbody>
                  </table>
                </div>
              </div>
              <div class="card-footer border-top">
                <div class="row">
                  <div class="col">
                    <!-- ================================ links advertisers Content Start ======================== -->
                     {!! $advertisers->links() !!}
                     <!-- ================================ links advertisers Content Start ======================== -->
                  </div>
                  <div class="col text-right view-report">
                    @if(COUNT($advertisers) != NULL)
                    <a>Showing 10 to {{ COUNT($advertisers) }} of {{ COUNT($advertisers) }} advertisers</a>
                    @else
                    <a>Showing 10 to 0 of 0 advertisers</a>
                    @endif
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- ============================================================= Content Start ============================================================= -->
      </div>
      <!-- ============================================================= Content Start ============================================================= -->
@endsection