routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
|--------------------------------------------------------------------------
| English
|--------------------------------------------------------------------------
|
*/
Route::get('English', function () {
    Session::put('lang', 'English');

    return Redirect('/');
});
/*
|--------------------------------------------------------------------------
| Arabic
|--------------------------------------------------------------------------
|
*/
Route::get('arabic', function () {
    Session::put('lang', 'arabic');

    return Redirect('/');
});
/*
|--------------------------------------------------------------------------
| German
|--------------------------------------------------------------------------
|
*/
Route::get('German', function () {
    Session::put('lang', 'German');

    return Redirect('/');
});

/*
|--------------------------------------------------------------------------
| Auth Routes
|--------------------------------------------------------------------------
|
*/
Auth::routes();
/*
|--------------------------------------------------------------------------
| Home Routes
|--------------------------------------------------------------------------
|
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('about', 'HomeController@about')->name('about');
Route::get('Contact', 'HomeController@Contact')->name('Contact');

/*
|--------------------------------------------------------------------------
| missing RETURN 404 PAGE Route
|--------------------------------------------------------------------------
|
*/
Route::get('missing', function () {
    return view('404');
});
/*
|--------------------------------------------------------------------------
| dashboardController
|--------------------------------------------------------------------------
|
*/
Route::group(['middleware' => 'admin'], function () {
    Route::resource('admin', 'dashboardController');
    Route::resource('dashboard/dashboardSettings', 'dashboardSettingsController');
    Route::resource('dashboard/dashboardUsers', 'AdminUserController');
    Route::resource('dashboard/dashboardRoles', 'dashboardRoleController');
    Route::resource('dashboard/dashboardPosts', 'dashboardPostController');
    Route::resource('dashboard/dashboardCategores', 'dashboardCategoryController');
    Route::resource('dashboard/dashboardMenus', 'dashboardmenuController');
    Route::resource('dashboard/dashboardMenu-items', 'dashboardmenu_itemController');
    Route::resource('dashboard/dashboardAds', 'dashboardvertiserController');
    Route::resource('dashboard/dashboardCauses', 'dashboardCauseController');
    Route::resource('dashboard/dashboardEvents', 'dashboardEventController');
    Route::resource('dashboard/dashboardMessages', 'dashboardmessageController');
    Route::resource('dashboard/dashboardGalleres', 'dashboardGalleryController');
});
/*
|--------------------------------------------------------------------------
| resource
|--------------------------------------------------------------------------
|
*/
Route::resource('Causes', 'CauseController');
Route::resource('Events', 'EventController');
Route::resource('Posts', 'PostController');
Route::resource('Comments', 'CommentController');
Route::resource('Messages', 'messageController');
// route for processing payment
Route::post('paypal', 'PaymentController@payWithpaypal');
// route for check status of the payment
Route::get('status', 'PaymentController@getPaymentStatus');

resources/views/english/Contact.blade.php
@extends('english.layout.main')

@section('content')
<!-- ============================================================= Content Start ============================================================= -->
<!--================ Start top-section Area =================-->
<style type="text/css">
  .banner-area{background:url('{{ asset(Setting()->HomePicture) }}') no-repeat;background-size:cover}
</style>
<section class="banner-area relative">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row justify-content-lg-end align-items-center banner-content">
      <div class="col-lg-5">
        <h1 class="text-white">Contact Us</h1>
        <!-- ===============================  Contact  ======================================== -->
        <p>{{ Setting()->about_en }}</p>
        <!-- ===============================  Contact  ======================================== -->
      </div>
    </div>
  </div>
      <div class="shape-bottom overflow-hidden">
        <img src="{{asset('assets/img/hero-shape.svg')}}" alt=" shape" class="bottom-shape">
    </div>
</section>
<!-- =============== End top-section Area =================== -->
<!-- ================ contact section start ================= -->
<section class="section-gap">
  <div class="container">
    <div class="d-none d-sm-block mb-5 pb-4" style="overflow: hidden;">
      <!-- ===============================  Contact  ======================================== -->
      <iframe src="{!! Setting()->Googlemap !!}" width="1200" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
    <div class="row">
      <div class="col-12">
        <h2 class="contact-title">Get in Touch</h2>
        <!-- ===============================  Contact  ======================================== -->
        @if(session('Messagge'))
        <div class="alert alert-success" role="alert">
          Congratulations. Your Message has been Send successfully
        </div>
        @endif
        <!-- ===============================  Contact  ======================================== -->
      </div>
      <div class="col-lg-8">
        <!-- ===============================  Contact  ======================================== -->
        <form class="form-contact contact_form" method="post" action="{{ route('Messages.store') }}" enctype="multipart/form-data">
          {{ csrf_field() }}
          <div class="row">
            <div class="col-12">
              <div class="form-group">
                <textarea class="form-control w-100" name="Content" id="Content" cols="30" rows="9" placeholder="Enter Message"></textarea>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <input class="form-control" name="name" id="name" type="text" placeholder="Enter your name">
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <input class="form-control" name="email" id="email" type="email" placeholder="Enter email address">
              </div>
            </div>
            <div class="col-12">
              <div class="form-group">
                <input class="form-control" name="subject" id="subject" type="text" placeholder="Enter Subject">
              </div>
            </div>
          </div>
          <div class="form-group mt-2 mb-5 mb-lg-0">
            <button type="submit" class="button button-contactForm primary-btn">Send Message</button>
          </div>
        </form>
        <!-- ===============================  Contact  ======================================== -->
      </div>
      <div class="col-lg-4">
        <div class="media contact-info">
          <span class="contact-info__icon"><i class="icon-material-outline-location-on"></i></span>
          <div class="media-body">
            <h3>Head Office</h3>
            <!-- ===============================  Contact  ======================================== -->
            <p>{{ Setting()->Location }}</p>
            <!-- ===============================  Contact  ======================================== -->
          </div>
        </div>
        <div class="media contact-info">
          <span class="contact-info__icon"><i class="icon-feather-phone"></i></span>
          <div class="media-body">
            <!-- ===============================  Contact  ======================================== -->
            <h3><a href="tel:{{ Setting()->PhoneNumber }}">{{ Setting()->PhoneNumber }}</a></h3>
            <!-- ===============================  Contact  ======================================== -->
          </div>
        </div>
        <div class="media contact-info">
          <span class="contact-info__icon"><i class="icon-material-outline-email"></i></span>
          <div class="media-body">
            <!-- ===============================  Contact  ======================================== -->
            <h3><a href="mailto:support@colorlib.com">{{ Setting()->Email }}</a></h3>
            <!-- ===============================  Contact  ======================================== -->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================ contact section end ================= -->
<!-- ============================================================= Content end   ============================================================= -->
@endsection

resources/views/english/about.blade.php
@extends('english.layout.main')

@section('content')
<!-- ============================================================= Content Start ============================================================= -->
    <!--================ Start top-section Area =================-->
    <style type="text/css">
        .banner-area{background:url('{{ asset(Setting()->HomePicture) }}') no-repeat;background-size:cover}
    </style>
    <!-- ===============================  About  ======================================== -->
    <section class="banner-area relative">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row justify-content-lg-end align-items-center banner-content">
                <div class="col-lg-5">
                    <h1 class="text-white">About Us</h1>
                    <!-- ===============================  About  ======================================== -->
                    <p>{!! Setting()->about_en !!}</p>
                    <!-- ===============================  About  ======================================== -->
                </div>
            </div>
        </div>
            <div class="shape-bottom overflow-hidden">
        <img src="{{asset('assets/img/hero-shape.svg')}}" alt=" shape" class="bottom-shape">
    </div>
    </section>
    <!--================ End top-section Area =================-->
    <!--================ Start About Area =================-->
    <section class="about_area lite_bg">
        <style type="text/css">
            .about_area .about_bg{
                background:linear-gradient(0deg, rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
                url('{{ asset(Setting()->AboutPicture) }}');background-repeat:no-repeat;background-size:cover;
                background-size:cover;
                position:absolute;right:0;top:0;height:100%;width:50%;z-index:-1}
        </style>
        <div class="container">
            <div class="row align-items-end">
                <div class="col-lg-5">
                    <div class="about_details lite_bg">
                        <!-- ===============================  About  ======================================== -->
                        <h2>{!! Setting()->title_about_en !!}</h2>
                        <!-- ===============================  About  ======================================== -->
                        <p class="mb-0">
                            {!! Setting()->content_about_en !!}
                        </p>
                        <!-- ===============================  About  ======================================== -->
                        <a href="{{ url('about') }}" class="primary-btn mt-5">
                            Read more
                            <i class="ti-angle-right ml-1"></i>
                        </a>
                        <!-- ===============================  About  ======================================== -->
                    </div>
                </div>
                <div class="col-lg-4 offset-lg-3 col-md-6 offset-md-1 d-lg-block d-none">
                    <div class="about_right">
                        <div class="video-inner justify-content-center align-items-center d-flex">
                            <!-- ===============================  About  ======================================== -->
                            <a id="play-home-video" class="video-play-button" href="{!! Setting()->video !!}">
                                <span></span>
                            </a>
                            <!-- ===============================  About  ======================================== -->
                        </div>
                    </div>
                </div>
            </div>
            <div class="about_bg d-lg-block d-none"></div>
        </div>
    </section>
    <!--================ End About Area =================-->
    <!--================ Start callto Area =================-->
    <section class="callto-area section-gap relative">
        <div class="overlay overlay-bg"></div>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <p class="top_text">Need your help?</p>
                    <div class="call-wrap mx-auto">
                        <h1>Volunteer Needed At Your Area</h1>
                        <p>In that Our I own life unto lights them two appear days rule thing fly main for main cause fowl itself dry
                            from made main cause fowl itself dry.</p>
                            <!-- ===============================  About  ======================================== -->
                        <a href="{{ route('register') }}" class="primary-btn mt-5">
                            Sign up
                            <i class="ti-angle-right ml-1"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================ End callto Area =================-->
<!-- ============================================================= Content end   ============================================================= -->
@endsection